#!/usr/bin/env sh

# Disable screen saver and power management
xset -dpms
xset s off
xset s noblank

# Hide Chromium warning bar
sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences

# Window size
GEO="$(fbset -s | awk '$1 == "geometry" { print $2":"$3 }')"
WIDTH=$(echo "$GEO" | cut -d: -f1)
HEIGHT=$(echo "$GEO" | cut -d: -f2)

# Launch browser in kiosk mode
unclutter &
chromium-browser http://localhost/ \
  --start-fullscreen \
  --window-size=$WIDTH,$HEIGHT \
  --window-position=0,0
  --kiosk \
  --incognito \
  --noerrdialogs \
  --disable-translate \
  --no-first-run \
  --fast \
  --fast-start \
  --disable-infobars \
  --disable-features=TranslateUI \
  --disk-cache-dir=/dev/null \
  --overscroll-history-navigation=0 \
  --disable-pinch